name: CheckDraft

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:          
  check-draft:
    name: Decide if the workflow runs
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - run: echo github.event.pull_request.draft

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: check-draft
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: g++

    - name: Compile C++ code
      run: |
        g++ -o ci_warnings ci_warnings.cpp
