name: CheckDraft

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'test/**'
      - 'tools/**'
      - '!tools/pythonpkg/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Python.yml'
      - '.github/config/out_of_tree_extensions.cmake'
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:          
  heck-draft:
    name: Don't trigger further jobs to run on draft PR
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - run: echo ${{ github.event.pull_request.draft }}

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: check-draft
    if: ${{ needs.check-draft.outputs.is_draft == false }}

    steps:
    - run: echo ${{needs.check-draft.outputs.is_draft}}

  another-test:
    name: Another Test
    runs-on: ubuntu-24.04
    needs: check-draft
    if: ${{ needs.check-draft.outputs.is_draft == true }}

    steps:
    - run: ${{needs.check-draft.outputs.is_draft}}
